### ISSUE TITLE
connect : Connection refused, can't connect to internet

### ISSUE THREAD

**Issue by Aromakelapa** [abdoxfox/http-ssl-ssh-injector#13] opened 2022-05-25 18:45 UTC
CONNECTED SUCCESSFULLY 
---Tunneling  starts-----
1653503999.991441 notice main.c:165 main(...) redsocks started, conn_max=128
1653504005.737421 info redsocks.c:1243 redsocks_accept_client(...) [192.168.8.149:37222->208.95.112.1:80]: accepted
1653504020.393636 info redsocks.c:1243 redsocks_accept_client(...) [192.168.8.149:54202->31.13.95.60:443]: accepted
1653504020.394174 notice utils.c:223 red_is_socket_connected_ok(...) connect: Connection refused
1653504020.394384 notice redsocks.c:958 redsocks_relay_connected(...) [192.168.8.149:54202->31.13.95.60:443]: red_is_socket_connected_ok: Connection refused
1653504020.394585 info redsocks.c:689 redsocks_drop_client(...) [192.168.8.149:54202->31.13.95.60:443]: dropping client (R/W), relay (R/W), idle 0.000415s
1653504020.491883 info redsocks.c:1243 redsocks_accept_client(...) [192.168.8.149:54206->31.13.95.60:443]: accepted
1653504020.492345 notice utils.c:223 red_is_socket_connected_ok(...) connect: Connection refused

Connected succesfully
![image](https://user-images.githubusercontent.com/66982638/170344558-936b51e5-949c-467c-9e6e-83df4c6812db.png)

When i trace my ip, no ceonnection
![image](https://user-images.githubusercontent.com/66982638/170344932-d375c6c5-d053-4b5c-8cdd-9768d4622f0a.png)

but if i use termux on android, it works and connect: max Conn (ping)
and when i trace my ip its showing my ip

any mistakes? 

*sorrymygrammar

**Comment by Sewmina7** [comment] 2022-05-30 16:53
The issue is that the proxy crashes for some reason when the proxification kicks in, I made a little workaround and opened a PR. Hopefully will be merged soon, or you can use my fork https://github.com/Sewmina7/http-ssl-ssh-injector

**Comment by abdoxfox** [comment] 2022-06-01 18:47
i merged a pull request from @Sewmina7 that should fix that issue
Try to update the repo and let's me if it works or syill refusing connection

**Comment by Aromakelapa** [comment] 2022-06-02 07:09
> i merged a pull request from @Sewmina7 that should fix that issue Try to update the repo and let's me if it works or syill refusing connection

Still connection refused sir
![image](https://user-images.githubusercontent.com/66982638/171573352-df4ebd0c-3bb3-488c-bbe1-66e8699746e3.png)

**Comment by Aromakelapa** [comment] 2022-06-02 07:10
> i merged a pull request from @Sewmina7 that should fix that issue Try to update the repo and let's me if it works or syill refusing connection

still connection refused sir

![image](https://user-images.githubusercontent.com/66982638/171573602-c78c65f0-5a35-4f9f-b60d-02499d543fa4.png)

**Comment by abdoxfox** [comment] 2022-06-02 12:24
Reach me on telegram for more details
my id : @Abdoxfox_official

**Comment by abdoxfox** [comment] 2022-06-03 17:01
So I hope it will works fine now after removed UDP rule ,that cause some fails

**Comment by Aromakelapa** [comment] 2022-06-05 06:37
> So I hope it will works fine now after removed UDP rule ,that cause some fails

still refuse

**Comment by abdoxfox** [comment] 2022-09-14 22:41
a new update will solve that issue is coming..

**Comment by abdoxfox** [comment] 2022-09-22 11:31
Fixed

**Closed** 2022-09-22 11:30 UTC
